### ISSUE TITLE
[macOS] Unable to compile `flutter_webrtc` 0.6.9+

### ISSUE THREAD

**Issue by simpleshadow** [cloudwebrtc/flutter-webrtc#719]
**Describe the bug**
Running `pub get` for any version of `flutter_webrtc` >= 0.6.9 will not compile on macOS 11.6 (darwin-arm).

Have tried `flutter clean` to no avail.

Receive the following error:
```
$ flutter run      
Launching lib/main.dart on macOS in debug mode...
Running pod install...                                             855ms
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:x86_64, id:2CF15756-D754-539C-BFE9-AB40BCBCEBFF }
{ platform:macOS, name:Any Mac }
/opt/homebrew/Caskroom/flutter/2.5.2/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.6.10+hotfix.1/macos/Classes/FlutterWebRTCPlugin.m:69:5: error: unknown type name 'RTCVideoEncoderFactorySimulcast'; did you mean 'RTCVideoEncoderFactoryH264'?
    RTCVideoEncoderFactorySimulcast *simulcastFactory = [[RTCVideoEncoderFactorySimulcast alloc]  initWithPrimary:encoderFactory
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    RTCVideoEncoderFactoryH264
In module 'WebRTC' imported from /opt/homebrew/Caskroom/flutter/2.5.2/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.6.10+hotfix.1/macos/Classes/FlutterWebRTCPlugin.h:8:
/Users/simple/Documents/git/github_graphql_client/macos/Flutter/ephemeral/.symlinks/plugins/flutter_webrtc/macos/WebRTC.framework/Headers/RTCVideoEncoderFactoryH264.h:17:12: note: 'RTCVideoEncoderFactoryH264' declared here
@interface RTCVideoEncoderFactoryH264 : NSObject <RTCVideoEncoderFactory>
           ^
/opt/homebrew/Caskroom/flutter/2.5.2/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.6.10+hotfix.1/macos/Classes/FlutterWebRTCPlugin.m:69:59: error: unknown receiver 'RTCVideoEncoderFactorySimulcast'; did you mean 'RTCVideoEncoderFactoryH264'?
    RTCVideoEncoderFactorySimulcast *simulcastFactory = [[RTCVideoEncoderFactorySimulcast alloc]  initWithPrimary:encoderFactory
                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                          RTCVideoEncoderFactoryH264
In module 'WebRTC' imported from /opt/homebrew/Caskroom/flutter/2.5.2/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.6.10+hotfix.1/macos/Classes/FlutterWebRTCPlugin.h:8:
/Users/simple/Documents/git/github_graphql_client/macos/Flutter/ephemeral/.symlinks/plugins/flutter_webrtc/macos/WebRTC.framework/Headers/RTCVideoEncoderFactoryH264.h:17:12: note: 'RTCVideoEncoderFactoryH264' declared here
@interface RTCVideoEncoderFactoryH264 : NSObject <RTCVideoEncoderFactory>
           ^
/opt/homebrew/Caskroom/flutter/2.5.2/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.6.10+hotfix.1/macos/Classes/FlutterWebRTCPlugin.m:69:99: error: no visible @interface for 'RTCVideoEncoderFactoryH264' declares the selector 'initWithPrimary:fallback:'
    RTCVideoEncoderFactorySimulcast *simulcastFactory = [[RTCVideoEncoderFactorySimulcast alloc]  initWithPrimary:encoderFactory
                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 errors generated.
note: Using new build system
note: Planning
note: Build preparation complete
note: Building targets in parallel
** BUILD FAILED **

Building macOS application...                                           
Exception: Build process failed
```

**Workaround**
Use 0.6.8.

**To Reproduce**
Add `flutter_webrtc` ^0.6.10 to `pubspec.yaml` and `flutter run` on macOS 11.6 (darwin-arm).

**Expected behavior**
Project compiles and runs.

**Platform information**

* **Flutter version**: 2.5.2
* **Plugin version**: 0.6.9+
* **OS**: macOS
* **OS version**: 11.6 (darwin-arm)

**Comment by hiroshihorie** [comment]
@cloudwebrtc I think the only reason it doesn't compile because we are not using the new WebRTC lib for MacOS, I think we don't need to turn off simulcast. What do you think ?
